### PR TITLE
Support `QueryParam` and `QueryParams`

### PR DESCRIPTION
**Pull request by joneshf**
From a discussion on slack: https://functionalprogramming.slack.com/archives/C04NA444H/p1511128410000043

Looks like these were missing.

Hope the formatting changes aren't too big to deal with. It's from purs ide on 0.11.7. If so, let me know and I can back them out.

### CODE REVIEW

**Comment by joneshf** [comment]
Not sure how you'd like to handle the dependency failure, but I'm more than happy to submit a separate PR that fixes that and merge master here.

**Comment by owickstrom** [comment]
Hey, cool, thanks for the PR! I'm good with the formatting changes, doesn't matter. And if you want to solve the dependency issue in this PR, that's fine by me.

**Comment by joneshf** [comment]
Pushed a fix!

**Comment by owickstrom** [comment]
Nice, thanks!

**Comment by owickstrom** [comment]
Released 0.10.0 with your fix to match purescript-trout.

**Comment by joneshf** [comment]
Thanks much!

**Pull request merged**
